api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/ld+json']
    swagger:
        versions: [3]
    collection:
        pagination:
            client_items_per_page: true # Disabled by default
            items_per_page_parameter_name: itemsPerPage # Default value
            client_enabled: true
            enabled_parameter_name: pagination # optional

